In [2]:
import pandas as pd
from sqlalchemy import create_engine

In [3]:
from sqlalchemy import create_engine

username = "root"
password = "Priyasaini_16092005"

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@localhost:3306/insightcart"
)

print("Connected Successfully")

Connected Successfully

In [4]:
customers = pd.read_sql("SELECT * FROM customers", engine)

In [5]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [6]:
customers.dtypes

customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

In [7]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [8]:
customers.duplicated().sum()

np.int64(0)

In [9]:
customers.nunique()

customer_id                 99441
customer_unique_id          96096
customer_zip_code_prefix    14994
customer_city                4119
customer_state                 27
dtype: int64

In [10]:
customers["customer_city"].head(20)

0                    franca
1     sao bernardo do campo
2                 sao paulo
3           mogi das cruzes
4                  campinas
5            jaragua do sul
6                 sao paulo
7                   timoteo
8                  curitiba
9            belo horizonte
10            montes claros
11           rio de janeiro
12         lencois paulista
13                sao paulo
14            caxias do sul
15               piracicaba
16           rio de janeiro
17                guarulhos
18                sao paulo
19                   pacaja
Name: customer_city, dtype: object

In [11]:
customers["customer_city"] = customers["customer_city"].str.strip()

In [12]:
customers["customer_city"] = customers["customer_city"].str.lower()

In [13]:
customers["customer_city"].head(20)

0                    franca
1     sao bernardo do campo
2                 sao paulo
3           mogi das cruzes
4                  campinas
5            jaragua do sul
6                 sao paulo
7                   timoteo
8                  curitiba
9            belo horizonte
10            montes claros
11           rio de janeiro
12         lencois paulista
13                sao paulo
14            caxias do sul
15               piracicaba
16           rio de janeiro
17                guarulhos
18                sao paulo
19                   pacaja
Name: customer_city, dtype: object

In [14]:
customers.to_sql(
    name="customers",
    con=engine,
    if_exists="replace",
    index=False
)

print("✅ Cleaned Customers table saved.")

✅ Cleaned Customers table saved.

In [15]:
orders = pd.read_sql("SELECT * FROM orders", engine)

In [16]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [17]:
orders.dtypes

order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

In [18]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_columns:
    orders[col] = pd.to_datetime(orders[col])

In [19]:
orders.dtypes

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

In [20]:
orders["order_purchase_timestamp"].dt.year

0        2017
1        2018
2        2018
3        2017
4        2018
         ...
99436    2017
99437    2018
99438    2017
99439    2018
99440    2018
Name: order_purchase_timestamp, Length: 99441, dtype: int32

In [21]:
orders["order_purchase_timestamp"].dt.month

0        10
1         7
2         8
3        11
4         2
         ..
99436     3
99437     2
99438     8
99439     1
99440     3
Name: order_purchase_timestamp, Length: 99441, dtype: int32

In [22]:
orders["order_purchase_timestamp"].dt.day

0         2
1        24
2         8
3        18
4        13
         ..
99436     9
99437     6
99438    27
99439     8
99440     8
Name: order_purchase_timestamp, Length: 99441, dtype: int32

In [23]:
orders["order_purchase_timestamp"].dt.hour

0        10
1        20
2         8
3        19
4        21
         ..
99436     9
99437    12
99438    14
99439    21
99440    20
Name: order_purchase_timestamp, Length: 99441, dtype: int32

In [24]:
orders["order_purchase_timestamp"].dt.day_name()

0           Monday
1          Tuesday
2        Wednesday
3         Saturday
4          Tuesday
           ...
99436     Thursday
99437      Tuesday
99438       Sunday
99439       Monday
99440     Thursday
Name: order_purchase_timestamp, Length: 99441, dtype: object

In [25]:
orders[date_columns].isnull().sum()

order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [26]:
orders["purchase_year"] = orders["order_purchase_timestamp"].dt.year

In [27]:
orders["purchase_month"] = orders["order_purchase_timestamp"].dt.month

In [28]:
orders["purchase_month_name"] = orders["order_purchase_timestamp"].dt.month_name()

In [29]:
orders["purchase_weekday"] = orders["order_purchase_timestamp"].dt.day_name()

In [30]:
orders["purchase_hour"] = orders["order_purchase_timestamp"].dt.hour

In [31]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,purchase_year,purchase_month,purchase_month_name,purchase_weekday,purchase_hour
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,2017,10,October,Monday,10
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,2018,7,July,Tuesday,20
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,2018,8,August,Wednesday,8
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,2017,11,November,Saturday,19
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2018,2,February,Tuesday,21

In [32]:
orders["delivery_days"] = (
    orders["order_delivered_customer_date"] -
    orders["order_purchase_timestamp"]
).dt.days

In [33]:
orders[[
    "order_purchase_timestamp",
    "order_delivered_customer_date",
    "delivery_days"
]].head()

  order_purchase_timestamp order_delivered_customer_date  delivery_days
0      2017-10-02 10:56:33           2017-10-10 21:25:13            8.0
1      2018-07-24 20:41:37           2018-08-07 15:27:45           13.0
2      2018-08-08 08:38:49           2018-08-17 18:06:29            9.0
3      2017-11-18 19:28:06           2017-12-02 00:28:42           13.0
4      2018-02-13 21:18:39           2018-02-16 18:17:02            2.0

In [34]:
orders["delivery_days"].mean()

np.float64(12.094085575687217)

In [35]:
orders["delivery_delay"] = (
    orders["order_delivered_customer_date"] -
    orders["order_estimated_delivery_date"]
).dt.days

In [36]:
orders[[
    "order_estimated_delivery_date",
    "order_delivered_customer_date",
    "delivery_delay"
]].head()

  order_estimated_delivery_date order_delivered_customer_date  delivery_delay
0                    2017-10-18           2017-10-10 21:25:13            -8.0
1                    2018-08-13           2018-08-07 15:27:45            -6.0
2                    2018-09-04           2018-08-17 18:06:29           -18.0
3                    2017-12-15           2017-12-02 00:28:42           -13.0
4                    2018-02-26           2018-02-16 18:17:02           -10.0

In [37]:
orders["delivery_days"].describe()

count    96476.000000
mean        12.094086
std          9.551746
min          0.000000
25%          6.000000
50%         10.000000
75%         15.000000
max        209.000000
Name: delivery_days, dtype: float64

In [38]:
orders[orders["delivery_delay"] > 0].head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,purchase_year,purchase_month,purchase_month_name,purchase_weekday,purchase_hour,delivery_days,delivery_delay
20,203096f03d82e0dffbc41ebc2e2bcfb7,d2b091571da224a1b36412c18bc3bbfe,delivered,2017-09-18 14:31:30,2017-09-19 04:04:09,2017-10-06 17:50:03,2017-10-09 22:23:46,2017-09-28,2017,9,September,Monday,14,21.0,11.0
25,fbf9ac61453ac646ce8ad9783d7d0af6,3a874b4d4c4b6543206ff5d89287f0c3,delivered,2018-02-20 23:46:53,2018-02-22 02:30:46,2018-02-26 22:25:22,2018-03-21 22:03:54,2018-03-12,2018,2,February,Tuesday,23,28.0,9.0
41,6ea2f835b4556291ffdc53fa0b3b95e8,c7340080e394356141681bd4c9b8fe31,delivered,2017-11-24 21:27:48,2017-11-25 00:21:09,2017-12-13 21:14:05,2017-12-28 18:59:23,2017-12-21,2017,11,November,Friday,21,33.0,7.0
57,66e4624ae69e7dc89bd50222b59f581f,684fa6da5134b9e4dab731e00011712d,delivered,2018-03-09 14:50:15,2018-03-09 15:40:39,2018-03-15 00:31:19,2018-04-03 13:28:46,2018-04-02,2018,3,March,Friday,14,24.0,1.0
58,a685d016c8a26f71a0bb67821070e398,911e4c37f5cafe1604fe6767034bf1ae,delivered,2017-03-13 18:14:36,2017-03-13 18:14:36,2017-03-22 14:03:09,2017-04-06 13:37:16,2017-03-30,2017,3,March,Monday,18,23.0,7.0

In [39]:
orders[orders["delivery_delay"] < 0].head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,purchase_year,purchase_month,purchase_month_name,purchase_weekday,purchase_hour,delivery_days,delivery_delay
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,2017,10,October,Monday,10,8.0,-8.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,2018,7,July,Tuesday,20,13.0,-6.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,2018,8,August,Wednesday,8,9.0,-18.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,2017,11,November,Saturday,19,13.0,-13.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2018,2,February,Tuesday,21,2.0,-10.0